Feat: Add long term statistics
fuatakgun/kia_uvo pull request #236
Opened 2022-01-05 08:05 UTC by rsegers

This PR adds [long term statistics](https://data.home-assistant.io/docs/statistics/) for the following sensors:
- EV Battery
- EV Range
- Total Range
- Odometer

Other (non-EV) sensors might be interesting as well to add as long term statistics in HA, but I am only able to test EV-sensors.

2022-01-05 20:55 UTC, cdnninja commented
Could we re-use the existing entity instead of two classes for this?

2022-01-06 11:28 UTC, rsegers commented
Multiple inheritance for ```InstrumentSensor``` also works. Hadn't thought of that. Updated PR.

2022-01-06 12:22 UTC, fuatakgun requested changes
i forgot to publish my comments :)

2022-01-06 12:33 UTC, rsegers commented on custom_components/kia_uvo/sensor.py
> +class InstrumentSensor(KiaUvoSensorEntity):
I think our comments just crossed each other :) I removed the ```KiaUvoSensorEntity``` class in favor of inheriting ```SensorEntity``` at ````InstrumentSensor````

2022-01-06 12:52 UTC, fuatakgun commented on custom_components/kia_uvo/sensor.py
> +class InstrumentSensor(KiaUvoSensorEntity):
i am not good at using GitHub efficiently yet :-) looks good, thanks

2022-01-06 12:54 UTC, fuatakgun commented
LGTM, @cdnninja please also check too.

2022-01-07 15:40 UTC, merged